name: Python CI Build Test

permissions:
  contents: read
  actions: read

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v4

      - name: Install UV
        run: bash scripts/install-uv.sh

      - name: Set up virtual environment
        run: bash scripts/venv.sh

      - name: Run Emulator
        # pls note this job runs the emulator and handles timeout to force stop server so that the build doesnt run indefinitely
        run: |
          timeout 10s bash scripts/start.sh 4 || code=$?
          if [ $code -eq 124 ]; then
            echo "Status: Server exited via timeout as expected"
          else
            echo "Failed with exit code $code"
            exit $code
          fi

      - name: Stop Emulator
        run: bash scripts/stop.sh